### ISSUE TITLE
Practical 6 not working!

### ISSUE THREAD

**Issue by tirthasheshpatel** [Shrey-Viradiya/OOPSEM3#1]
Update the files and help me with practical 6. Also, upload practical 6c and 6d.
Thanking you!
Yours most sincerely,
Tirth Patel

**Comment by Shrey-Viradiya** [comment]
practical 6c is complexDemo.java and practical 6D is GSSArrayDemo.java

**Comment by Shrey-Viradiya** [comment]
practical 6a is Rectangle.java and TempRect.java and practical 6b is Term.java
